GET http://localhost:5000/products/fetchdaftarproduk?search=obat HTTP/1.1
Content-Type: application/json

###
GET http://localhost:5000/products/getcategory HTTP/1.1
Content-Type: application/json


###

GET http://localhost:5000/products/component HTTP/1.1
Content-Type: application/json

###

GET http://localhost:5000/products/getlastproduct HTTP/1.1
Content-Type: application/json


###

GET http://localhost:5000/products/fetchuserproduct?category=1&order=price HTTP/1.1
Content-Type: application/json


###
GET http://localhost:5000/products/getusercategoryselected/1 HTTP/1.1
Content-Type: application/json


###
GET http://localhost:5000/products/getdetailproduct/1 HTTP/1.1
Content-Type: application/json


###
GET http://localhost:5000/products/getprodukterkait?brand=miracloven HTTP/1.1
Content-Type: application/json
