GET http://localhost:5000/transaction/getusertransaction HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6IkdyaXNlbGRhIEF0aGFsbGFoIFNpbHZpeWFuYSIsInJvbGVfaWQiOjAsImlhdCI6MTY1Nzk2NDUwNSwiZXhwIjoxNjU3OTkzMzA1fQ.yv23oLFvg34rEhzuJTB1WhkgipNmDTGOZVPWGj-RezY


###

GET http://localhost:5000/transaction/getdetailtransaction/19 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6ImFkbWluIiwicm9sZV9pZCI6IkFkbWluIiwiaWF0IjoxNjU4MjM1NjY4LCJleHAiOjE2NTgyNjQ0Njh9.9l5CLVB0gDgzF5RPvTUAQnVoaYTHe_2hvb0gUGzoCcw
###


GET http://localhost:5000/transaction/getalltransaction?from_date=2022-07-07&to_date=2022-07-09 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6ImFkbWluIiwicm9sZV9pZCI6IkFkbWluIiwiaWF0IjoxNjU4MzE0NjQ4LCJleHAiOjE2NTgzNDM0NDh9.PYjHU8uMMQFHW4O4fuTdwwxj_L9lZJnyqXhYNSTKXJM

###

GET  http://localhost:5000/transaction/getproductlog/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6IkdyaXNlbGRhIEF0aGFsbGFoIFNpbHZpeWFuYSIsInJvbGVfaWQiOjAsImlhdCI6MTY1Nzk2NDUwNSwiZXhwIjoxNjU3OTkzMzA1fQ.yv23oLFvg34rEhzuJTB1WhkgipNmDTGOZVPWGj-RezY
